package com.example.hseapp.dao


data class AnswerEntity(
    val namalokasi: String?,
    val namaloading: String?,
    val shift: String?,
    val grup: String?,
    val created_by_id: Int,
//    val updated_by_id: Int,
    val kondisi1: String?,
    val kode1: String?,
    val keterangan1: String?,
    val kondisi2: String?,
    val kode2: String?,
    val keterangan2: String?,
    val kondisi3: String?,
    val kode3: String?,
    val keterangan3: String?,
    val kondisi4: String?,
    val kode4: String?,
    val keterangan4: String?,
    val kondisi5: String?,
    val kode5: String?,
    val keterangan5: String?,
    val kondisi6: String?,
    val kode6: String?,
    val keterangan6: String?,
    val kondisi7: String?,
    val kode7: String?,
    val keterangan7: String?,
    val kondisi8: String?,
    val kode8: String?,
    val keterangan8: String?,
    val kondisi9: String?,
val kode9: String?,
val keterangan9: String?,
val kondisi10: String?,
val kode10: String?,
val keterangan10: String?,
val kondisi11: String?,
val kode11: String?,
val keterangan11: String?,
val kondisi12: String?,
val kode12: String?,
val keterangan12: String?,
val kondisi13: String?,
val kode13: String?,
val keterangan13: String?,
val kondisi14: String?,
val kode14: String?,
val keterangan14: String?,
val kondisi15: String?,
val kode15: String?,
val keterangan15: String?,
val kondisi16: String?,
val kode16: String?,
val keterangan16: String?,
val kondisi17: String?,
val kode17: String?,
val keterangan17: String?,
val kondisi18: String?,
val kode18: String?,
val keterangan18: String?,
val kondisi19: String?,
val kode19: String?,
val keterangan19: String?,
val kondisi20: String?,
val kode20: String?,
val keterangan20: String?,
val kondisi21: String?,
val kode21: String?,
val keterangan21: String?,
val kondisi22: String?,
val kode22: String?,
val keterangan22: String?,
val kondisi23: String?,
val kode23: String?,
val keterangan23: String?,
val kondisi24: String?,
val kode24: String?,
val keterangan24: String?,
val kondisi25: String?,
val kode25: String?,
val keterangan25: String?,
val kondisi26: String?,
val kode26: String?,
val keterangan26: String?,
val tanggal: String?,
val pengawas: String?,
val gambar1:String,
val gambar2:String,
    val tindakan1:String,
    val tindakan2:String,
    )

